# 超过 15 天的 issue 会自动被标记为陈旧 issue
daysUntilStale: 15
# issue 被标记为陈旧后，再过 15 天自动关闭
daysUntilClose: 15
# 带有下列标签的 issue 不会被标记为陈旧
exemptLabels:
  - 讨论
# 被标记为陈旧的标签名
staleLabel: 陈旧
# 被标记为陈旧时，机器人回复的内容
markComment: >
  这个 issue 已经十五天没有被回复过了，所以被自动标记为“陈旧”。
  如果再过十五天没有回复，这个 issue 就会被自动关闭。
# 被自动关闭时，机器人回复的内容
closeComment: >
  这个 issue 已经三十天没有任何回复了，被自动关闭。
