# 超过 15 天的 issue 会自动被标记为“过期” issue
daysUntilStale: 15

# issue 被标记为“过期”后，再过 10000 天自动关闭
daysUntilClose: 10000

# 带有下列标签的 issue 不会被标记为“过期”
exemptLabels:
  - 讨论
  - 公告

# 被标记为“过期”的 label 名
staleLabel: 过期

# 被标记为“过期”时，机器人回复的内容
markComment: >
  这个 issue 已经至少十五天没有任何回复了，所以被自动标记为“过期”。  
  建议尽快处理。  

# 被自动关闭时，机器人回复的内容
closeComment: >
  这个 issue 太久没有处理，被自动关闭。
